<?php 
pdo_query("
truncate table ims_ewei_shop_express;
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(1, '顺丰', 'shunfeng', 1, 0, 'JH_014', 'SF');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(2, '申通', 'shentong', 1, 0, 'JH_005', 'STO');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(3, '韵达快运', 'yunda', 1, 0, 'JH_003', 'YD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(4, '天天快递', 'tiantian', 1, 0, 'JH_004', 'HHTT');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(5, '圆通速递', 'yuantong', 1, 0, 'JH_002', 'YTO');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(6, '中通速递', 'zhongtong', 1, 0, 'JH_006', 'ZTO');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(7, 'ems快递', 'ems', 1, 0, 'JH_001', 'EMS');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(8, '百世快递', 'huitongkuaidi', 1, 0, 'JH_012', 'HTKY');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(9, '全峰快递', 'quanfengkuaidi', 1, 0, 'JH_009', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(10, '宅急送', 'zhaijisong', 1, 0, 'JH_007', 'ZJS');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(11, 'aae全球专递', 'aae', 1, 0, 'JHI_049', 'AAE');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(12, '安捷快递', 'anjie', 1, 0, '', 'AJ');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(13, '安信达快递', 'anxindakuaixi', 1, 0, 'JH_131', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(14, '彪记快递', 'biaojikuaidi', 1, 0, '', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(15, 'bht', 'bht', 1, 0, 'JHI_008', 'BHT');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(16, '百福东方国际物流', 'baifudongfang', 1, 0, 'JH_062', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(17, '中国东方（COE）', 'coe', 1, 0, 'JHI_038', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(18, '长宇物流', 'changyuwuliu', 1, 0, '', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(19, '大田物流', 'datianwuliu', 1, 0, 'JH_050', 'DTWL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(20, '德邦物流', 'debangwuliu', 1, 0, 'JH_011', 'DBL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(21, 'dhl', 'dhl', 1, 0, 'JHI_002', 'DHL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(22, 'dpex', 'dpex', 1, 0, 'JHI_011', 'DPEX');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(23, 'd速快递', 'dsukuaidi', 1, 0, 'JH_049', 'DSWL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(24, '递四方', 'disifang', 1, 0, 'JHI_080', 'D4PX');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(25, 'fedex（国外）', 'fedex', 1, 0, 'JHI_014', 'FEDEX_GJ');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(26, '飞康达物流', 'feikangda', 1, 0, 'JH_088', 'FKD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(27, '凤凰快递', 'fenghuangkuaidi', 1, 0, '', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(28, '飞快达', 'feikuaida', 1, 0, 'JH_151', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(29, '国通快递', 'guotongkuaidi', 1, 0, 'JH_010', 'GTO');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(30, '港中能达物流', 'ganzhongnengda', 1, 0, 'JH_033', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(31, '广东邮政物流', 'guangdongyouzhengwuliu', 1, 0, 'JH_135', 'GDEMS');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(32, '共速达', 'gongsuda', 1, 0, 'JH_039', 'GSD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(33, '恒路物流', 'hengluwuliu', 1, 0, 'JH_048', 'HLWL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(34, '华夏龙物流', 'huaxialongwuliu', 1, 0, 'JH_129', 'HXLWL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(35, '海红', 'haihongwangsong', 1, 0, 'JH_132', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(36, '海外环球', 'haiwaihuanqiu', 1, 0, 'JHI_013', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(37, '佳怡物流', 'jiayiwuliu', 1, 0, 'JH_035', 'JYWL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(38, '京广速递', 'jinguangsudikuaijian', 1, 0, 'JH_041', 'JGSD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(39, '急先达', 'jixianda', 1, 0, 'JH_040', 'JXD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(40, '佳吉物流', 'jiajiwuliu', 1, 0, 'JH_030', 'CNEX');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(41, '加运美物流', 'jymwl', 1, 0, 'JH_054', 'JYM');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(42, '金大物流', 'jindawuliu', 1, 0, 'JH_079', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(43, '嘉里大通', 'jialidatong', 1, 0, 'JH_060', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(44, '晋越快递', 'jykd', 1, 0, 'JHI_046', 'JYKD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(45, '快捷速递', 'kuaijiesudi', 1, 0, 'JH_008', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(46, '联邦快递（国内）', 'lianb', 1, 0, 'JH_122', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(47, '联昊通物流', 'lianhaowuliu', 1, 0, 'JH_021', 'LHT');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(48, '龙邦物流', 'longbanwuliu', 1, 0, 'JH_019', 'LB');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(49, '立即送', 'lijisong', 1, 0, 'JH_044', 'LJSKD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(50, '乐捷递', 'lejiedi', 1, 0, 'JH_043', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(51, '民航快递', 'minghangkuaidi', 1, 0, 'JH_100', 'MHKD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(52, '美国快递', 'meiguokuaidi', 1, 0, 'JHI_044', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(53, '门对门', 'menduimen', 1, 0, 'JH_036', 'MDM');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(54, 'OCS', 'ocs', 1, 0, 'JHI_012', 'OCS');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(55, '配思货运', 'peisihuoyunkuaidi', 1, 0, '', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(56, '全晨快递', 'quanchenkuaidi', 1, 0, 'JH_055', 'QCKD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(57, '全际通物流', 'quanjitong', 1, 0, 'JH_127', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(58, '全日通快递', 'quanritongkuaidi', 1, 0, 'JH_029', 'QRT');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(59, '全一快递', 'quanyikuaidi', 1, 0, 'JH_020', 'UAPEX');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(60, '如风达', 'rufengda', 1, 0, 'JH_017', 'RFD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(61, '三态速递', 'santaisudi', 1, 0, 'JH_065', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(62, '盛辉物流', 'shenghuiwuliu', 1, 0, 'JH_066', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(63, '速尔物流', 'suer', 1, 0, '', 'SURE');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(64, '盛丰物流', 'shengfeng', 1, 0, 'JH_082', 'SFWL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(65, '赛澳递', 'saiaodi', 1, 0, 'JH_042', 'SAD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(66, '天地华宇', 'tiandihuayu', 1, 0, 'JH_018', 'HOAU');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(67, 'tnt', 'tnt', 1, 0, 'JHI_003', 'TNT');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(68, 'ups', 'ups', 1, 0, 'JHI_004', 'UPS');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(69, '万家物流', 'wanjiawuliu', 1, 0, '', 'WJWL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(70, '文捷航空速递', 'wenjiesudi', 1, 0, '', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(71, '伍圆', 'wuyuan', 1, 0, '', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(72, '万象物流', 'wxwl', 1, 0, 'JH_115', 'WXWL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(73, '新邦物流', 'xinbangwuliu', 1, 0, 'JH_022', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(74, '信丰物流', 'xinfengwuliu', 1, 0, 'JH_023', 'XFEX');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(75, '亚风速递', 'yafengsudi', 1, 0, 'JH_075', 'YFSD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(76, '一邦速递', 'yibangwuliu', 1, 0, 'JH_064', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(77, '优速物流', 'youshuwuliu', 1, 0, 'JH_013', 'UC');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(78, '邮政快递包裹', 'youzhengguonei', 1, 0, 'JH_077', 'YZBK');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(79, '邮政国际包裹挂号信', 'youzhengguoji', 1, 0, '', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(80, '远成物流', 'yuanchengwuliu', 1, 0, 'JH_024', 'YCWL');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(81, '源伟丰快递', 'yuanweifeng', 1, 0, 'JH_141', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(82, '元智捷诚快递', 'yuanzhijiecheng', 1, 0, 'JH_126', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(83, '运通快递', 'yuntongkuaidi', 1, 0, 'JH_145', 'YTKD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(84, '越丰物流', 'yuefengwuliu', 1, 0, 'JH_068', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(85, '源安达', 'yad', 1, 0, 'JH_067', 'YADEX');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(86, '银捷速递', 'yinjiesudi', 1, 0, 'JH_148', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(87, '中铁快运', 'zhongtiekuaiyun', 1, 0, 'JH_015', 'ZTKY');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(88, '中邮物流', 'zhongyouwuliu', 1, 0, 'JH_027', 'ZYKD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(89, '忠信达', 'zhongxinda', 1, 0, 'JH_086', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(90, '芝麻开门', 'zhimakaimen', 1, 0, 'JH_026', '');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(91, '安能物流', 'annengwuliu', 1, 0, 'JH_059', 'ANE');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(92, '京东快递', 'jd', 1, 0, 'JH_046', 'JD');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(93, '微特派', 'weitepai', 1, 0, '', 'WTP');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(94, '九曳供应链', 'jiuyescm', 1, 0, '', 'JIUYE');
INSERT INTO `ims_ewei_shop_express` (`id`, `name`, `express`, `status`, `displayorder`, `code`, `coding`) VALUES(95, '跨越速运', 'kuayue', 1, 0, '', 'KYSY');

truncate table ims_ewei_shop_task_extension;
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(1, '推荐人数', 'commission_member', 1, 'number', 'commission', '推荐', '人');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(2, '分销佣金', 'commission_money', 1, 'number', 'commission', '达到', '元');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(3, '分销订单', 'commission_order', 1, 'number', 'commission', '达到', '笔');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(6, '订单满额', 'cost_enough', 1, 'number', 'cost', '满', '元');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(7, '累计金额', 'cost_total', 1, 'number', 'cost', '累计', '元');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(8, '订单数量', 'cost_count', 1, 'number', 'cost', '达到', '单');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(9, '指定商品', 'cost_goods', 1, 'select', 'cost', '购买指定商品', '件');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(10, '商品评价', 'cost_comment', 1, 'number', 'cost', '评价订单', '次');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(11, '累计充值', 'cost_rechargetotal', 1, 'number', 'cost', '达到', '元');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(12, '充值满额', 'cost_rechargeenough', 1, 'number', 'cost', '满', '元');
INSERT INTO `ims_ewei_shop_task_extension` (`id`, `taskname`, `taskclass`, `status`, `classify`, `classify_name`, `verb`, `unit`) VALUES(13, '绑定手机', 'member_info', 1, 'boole', 'member', '绑定手机号（必须开启wap或小程序）', '');

truncate table ims_ewei_shop_task_type;
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(13, 'child_agent', '下级分销商人数', '直属下级分销商人数，累计下级分销商人数达标,即可获得奖励', '直属下级分销商人数达', 1, '人', 0, 'primary', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(1, 'poster', '任务海报', '把生成的海报并分享给朋友，朋友扫描并关注公众号即可获得奖励。', '转发海报并吸引', 1, '人关注', 0, 'primary', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(2, 'info_phone', '绑定手机', '在个人中心中，绑定手机号，即可完成任务获得奖励。', '绑定手机', 0, '', 0, 'warning', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(3, 'order_first', '首次购物', '在商城中首次下单，即可获得奖励，必须确认收货。', '首次在商城中下单购物', 0, '', 0, 'warning', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(4, 'recharge_full', '单笔充值满额', '在商城中充值余额，单笔充值满额，即可获得奖励。', '单笔充值满', 1, '元', 0, 'success', 1);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(5, 'order_full', '单笔满额', '在商城中下单，单笔满额即可获得奖励，必须确认收货。', '单笔订单满', 1, '元', 0, 'success', 1);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(6, 'order_all', '累计消费', '在商城中购物消费，累计满额即可获得奖励，无需确认收货。', '购物总消费额达到', 1, '元', 0, 'success', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(7, 'pyramid_money', '分销佣金', '只有分销商可接此任务。累计分销佣金满额，即可完成任务。', '分销商获得佣金金额达', 1, '元', 0, 'primary', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(8, 'pyramid_num', '下级人数', '只有分销商可接此任务。累计下级人数达标，即可完成任务。', '分销商推荐下级人数达', 1, '人', 0, 'primary', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(9, 'comment', '商品好评', '任意给一个商品五星好评，即可完成任务获得奖励。', '给商品好评', 0, '', 0, 'warning', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(10, 'post', '社区发帖', '在社区中发表指定篇帖子，即可完成任务获得奖励。', '在论坛中发表', 1, '篇帖子', 0, 'warning', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(11, 'goods', '购买指定商品', '购买指定商品后即可完成任务，必须确认收货。', '购买指定商品', 0, '', 1, 'info', 0);
INSERT INTO `ims_ewei_shop_task_type` (`id`, `type_key`, `type_name`, `description`, `verb`, `numeric`, `unit`, `goods`, `theme`, `once`) VALUES(12, 'recharge_count', '累计充值满额', '在商城中充值余额，累计充值满额，即可获得奖励。', '累计充值满', 1, '元', 0, 'success', 0);

truncate table ims_ewei_shop_member_wxapp_message_template_type;
INSERT INTO `ims_ewei_shop_member_wxapp_message_template_type` VALUES (1,'好友瓜分券活动完成通知','friendcoupon_complete','AT0280','任务完成通知','8,15,11','friendcoupon','好友瓜分券');


truncate table ims_ewei_shop_exhelper_esheet;
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(1, '顺丰', 'shunfeng', 'SF', 'a:2:{i:0;a:4:{s:5:\"style\";s:9:\"二联150\";s:4:\"spec\";s:33:\"（宽100mm高150mm切点90/60）\";s:4:\"size\";s:3:\"150\";s:9:\"isdefault\";i:1;}i:1;a:4:{s:5:\"style\";s:9:\"三联210\";s:4:\"spec\";s:38:\"（宽100mm 高210mm 切点90/60/60）\";s:4:\"size\";s:3:\"210\";s:9:\"isdefault\";i:0;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(2, '百世快递', 'huitongkuaidi', 'HTKY', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联183\";s:4:\"spec\";s:37:\"（宽100mm 高183mm 切点87/5/91）\";s:4:\"size\";s:3:\"183\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(3, '韵达', 'yunda', 'YD', 'a:2:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:0;}i:1;a:4:{s:5:\"style\";s:9:\"二联203\";s:4:\"spec\";s:36:\"（宽100mm 高203mm 切点152/51）\";s:4:\"size\";s:3:\"203\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(4, '申通', 'shentong', 'STO', 'a:2:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}i:1;a:4:{s:5:\"style\";s:9:\"二联150\";s:4:\"spec\";s:35:\"（宽100mm 高150mm 切点90/60）\";s:4:\"size\";s:3:\"150\";s:9:\"isdefault\";i:0;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(5, '圆通', 'yuantong', 'YTO', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(6, 'EMS', 'ems', 'EMS', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联150\";s:4:\"spec\";s:33:\"（宽100mm高150mm切点90/60）\";s:4:\"size\";s:3:\"150\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(7, '中通', 'zhongtong', 'ZTO', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(8, '德邦', 'debangwuliu', 'DBL', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联177\";s:4:\"spec\";s:34:\"（宽100mm高177mm切点107/70）\";s:4:\"size\";s:3:\"177\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(9, '优速', 'youshuwuliu', 'UC', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(10, '宅急送', 'zhaijisong', 'ZJS', 'a:2:{i:0;a:4:{s:5:\"style\";s:9:\"二联120\";s:4:\"spec\";s:33:\"（宽100mm高116mm切点98/18）\";s:4:\"size\";s:3:\"120\";s:9:\"isdefault\";i:1;}i:1;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:0;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(11, '京东', 'jd', 'JD', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联110\";s:4:\"spec\";s:33:\"（宽100mm高110mm切点60/50）\";s:4:\"size\";s:3:\"110\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(12, '信丰', 'xinfengwuliu', 'XFEX', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联150\";s:4:\"spec\";s:33:\"（宽100mm高150mm切点90/60）\";s:4:\"size\";s:3:\"150\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(13, '全峰', 'quanfengkuaidi', 'QFKD', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(14, '跨越速运', 'kuayue', 'KYSY', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联137\";s:4:\"spec\";s:34:\"（宽100mm高137mm切点101/36）\";s:4:\"size\";s:3:\"137\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(15, '安能', 'annengwuliu', 'ANE', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"三联180\";s:4:\"spec\";s:37:\"（宽100mm高180mm切点110/30/40）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(16, '快捷', 'kuaijiesudi', 'FAST', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(17, '国通', 'guotongkuaidi', 'GTO', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(18, '天天', 'tiantian', 'HHTT', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(19, '中铁快运', 'zhongtiekuaiyun', 'ZTKY', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联150\";s:4:\"spec\";s:33:\"（宽100mm高150mm切点90/60）\";s:4:\"size\";s:3:\"150\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(20, '邮政快递包裹', 'youzhengguonei', 'YZPY', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联180\";s:4:\"spec\";s:34:\"（宽100mm高180mm切点110/70）\";s:4:\"size\";s:3:\"180\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(21, '邮政国内标快', 'youzhengguonei', 'YZBK', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联150\";s:4:\"spec\";s:33:\"（宽100mm高150mm切点90/60）\";s:4:\"size\";s:3:\"150\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(22, '全一快递', 'quanyikuaidi', 'UAPEX', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联150\";s:4:\"spec\";s:32:\"（宽90mm高150mm切点90/60）\";s:4:\"size\";s:3:\"150\";s:9:\"isdefault\";i:1;}}');
INSERT INTO `ims_ewei_shop_exhelper_esheet` (`id`, `name`, `express`, `code`, `datas`) VALUES(23, '速尔快递', 'sue', 'SURE', 'a:1:{i:0;a:4:{s:5:\"style\";s:9:\"二联150\";s:4:\"spec\";s:33:\"（宽100mm高150mm切点90/60）\";s:4:\"size\";s:3:\"150\";s:9:\"isdefault\";i:1;}}');



truncate table ims_ewei_shop_member_message_template_type;

INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(1, '订单付款通知', 'saler_pay', 'OPENTM405584202', '', '订单付款通知', '{{first.DATA}}订单编号：{{keyword1.DATA}}商品名称：{{keyword2.DATA}}商品数量：{{keyword3.DATA}}支付金额：{{keyword4.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(2, '自提订单提交成功通知', 'carrier', 'OPENTM201594720', '', '订单付款通知', '{{first.DATA}}自提码：{{keyword1.DATA}}商品详情：{{keyword2.DATA}}提货地址：{{keyword3.DATA}}提货时间：{{keyword4.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(3, '订单取消通知', 'cancel', 'OPENTM201764653', '', '订单关闭提醒', '{{first.DATA}}订单商品：{{keyword1.DATA}}订单编号：{{keyword2.DATA}}下单时间：{{keyword3.DATA}}订单金额：{{keyword4.DATA}}关闭时间：{{keyword5.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(4, '订单即将取消通知', 'willcancel', 'OPENTM201764653', '', '订单关闭提醒', '{{first.DATA}}订单商品：{{keyword1.DATA}}订单编号：{{keyword2.DATA}}下单时间：{{keyword3.DATA}}订单金额：{{keyword4.DATA}}关闭时间：{{keyword5.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(5, '订单支付成功通知', 'pay', 'OPENTM405584202', '', '订单支付通知', '{{first.DATA}}订单编号：{{keyword1.DATA}}商品名称：{{keyword2.DATA}}商品数量：{{keyword3.DATA}}支付金额：{{keyword4.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(6, '订单发货通知', 'send', 'OPENTM401874827', '', '订单发货通知', '{{first.DATA}}订单编号：{{keyword1.DATA}}快递公司：{{keyword2.DATA}}快递单号：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(7, '自动发货通知(虚拟物品及卡密)', 'virtualsend', 'OPENTM207793687', '', '自动发货通知', '{{first.DATA}}商品名称：{{keyword1.DATA}}订单号：{{keyword2.DATA}}订单金额：{{keyword3.DATA}}卡密信息：{{keyword4.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(8, '订单状态更新(修改收货地址)(修改价格)', 'orderstatus', 'TM00017', '', '订单付款通知', '{{first.DATA}}订单编号:{{OrderSn.DATA}}订单状态:{{OrderStatus.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(9, '退款成功通知', 'refund1', 'TM00430', '', '退款成功通知', '{{first.DATA}}退款金额：{{orderProductPrice.DATA}}商品详情：{{orderProductName.DATA}}订单编号：{{orderName.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(10, '换货成功通知', 'refund3', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(11, '退款申请驳回通知', 'refund2', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(12, '充值成功通知', 'recharge_ok', 'OPENTM207727673', '', '充值成功提醒', '{{first.DATA}}充值金额：{{keyword1.DATA}}充值时间：{{keyword2.DATA}}账户余额：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(13, '提现成功通知', 'withdraw_ok', 'OPENTM207422808', '', '提现通知', '{{first.DATA}}申请提现金额：{{keyword1.DATA}}取提现手续费：{{keyword2.DATA}}实际到账金额：{{keyword3.DATA}}提现渠道：{{keyword4.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(14, '会员升级通知(任务处理通知)', 'upgrade', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(15, '充值成功通知（后台管理员手动）', 'backrecharge_ok', 'OPENTM207727673', '', '充值成功提醒', '{{first.DATA}}充值金额：{{keyword1.DATA}}充值时间：{{keyword2.DATA}}账户余额：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(16, '积分变动提醒', 'backpoint_ok', 'OPENTM207509450', '', '积分变动提醒', '{{first.DATA}}获得时间：{{keyword1.DATA}}获得积分：{{keyword2.DATA}}获得原因：{{keyword3.DATA}}当前积分：{{keyword4.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(17, '换货发货通知', 'refund4', 'OPENTM401874827', '', '订单发货通知', '{{first.DATA}}订单编号：{{keyword1.DATA}}快递公司：{{keyword2.DATA}}快递单号：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(18, '砍价活动通知', 'bargain_message', 'OPENTM415477060', NULL, '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'bargain', '砍价消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(19, '拼团活动通知', 'groups', NULL, NULL, NULL, NULL, 'groups', '拼团消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(20, '人人分销通知', 'commission', NULL, NULL, NULL, NULL, 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(21, '商品付款通知', 'saler_goodpay', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(22, '砍到底价通知', 'bargain_fprice', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'bargain', '砍价消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(23, '订单收货通知(卖家)', 'saler_finish', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(24, '余额兑换成功通知', 'exchange_balance', 'OPENTM207727673', '', '充值成功提醒', '{{first.DATA}}充值金额：{{keyword1.DATA}}充值时间：{{keyword2.DATA}}账户余额：{{keyword3.DATA}}{{remark.DATA}}', 'exchange', '兑换中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(25, '积分兑换成功通知', 'exchange_score', 'OPENTM207509450', '', '积分变动提醒', '{{first.DATA}}获得时间：{{keyword1.DATA}}获得积分：{{keyword2.DATA}}获得原因：{{keyword3.DATA}}当前积分：{{keyword4.DATA}}{{remark.DATA}}', 'exchange', '兑换中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(26, '兑换中心余额充值通知', 'exchange_recharge', 'OPENTM207727673', '', '充值成功提醒', '{{first.DATA}}充值金额：{{keyword1.DATA}}充值时间：{{keyword2.DATA}}账户余额：{{keyword3.DATA}}{{remark.DATA}}', 'exchange', '兑换中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(27, '游戏中心通知', 'lottery_get', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'lottery', '抽奖消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(35, '库存预警通知', 'saler_stockwarn', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(36, '卖家核销商品核销通知', 'o2o_sverify', 'OPENTM409521536', '', '核销成功提醒', '{{first.DATA}}核销项目：{{keyword1.DATA}}核销时间：{{keyword2.DATA}}核销门店：{{keyword3.DATA}}{{remark.DATA}}', 'o2o', 'O2O消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(37, '核销商品核销通知', 'o2o_bverify', 'OPENTM409521536', '', '核销成功提醒', '{{first.DATA}}核销项目：{{keyword1.DATA}}核销时间：{{keyword2.DATA}}核销门店：{{keyword3.DATA}}{{remark.DATA}}', 'o2o', 'O2O消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(38, '卖家商品预约通知', 'o2o_snorder', 'OPENTM202447657', '', '预约成功提醒', '{{first.DATA}}预约项目：{{keyword1.DATA}}预约时间：{{keyword2.DATA}}{{remark.DATA}}', 'o2o', 'O2O消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(39, '商品预约成功通知', 'o2o_bnorder', 'OPENTM202447657', '', '预约成功提醒', '{{first.DATA}}预约项目：{{keyword1.DATA}}预约时间：{{keyword2.DATA}}{{remark.DATA}}', 'o2o', 'O2O消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(42, '商品下单通知', 'saler_goodsubmit', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(50, '维权订单通知', 'saler_refund', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sys', '系统消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(43, '任务接取通知', 'task_pick', 'OPENTM415477060', NULL, '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'task', '任务中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(44, '任务进度通知', 'task_progress', 'OPENTM415477060', NULL, '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'task', '任务中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(45, '任务完成通知', 'task_finish', 'OPENTM415477060', NULL, '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'task', '任务中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(46, '任务海报接取通知', 'task_poster_pick', 'OPENTM415477060', NULL, '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'task', '任务中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(47, '任务海报进度通知', 'task_poster_progress', 'OPENTM415477060', NULL, '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'task', '任务中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(48, '任务海报完成通知', 'task_poster_finish', 'OPENTM415477060', NULL, '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'task', '任务中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(49, '任务海报扫描通知', 'task_poster_scan', 'OPENTM415477060', NULL, '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'task', '任务中心消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(52, '成为分销商通知', 'commission_become', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(53, '新增下线通知', 'commission_agent_new', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(54, '下级付款通知', 'commission_order_pay', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(55, '下级确认收货通知', 'commission_order_finish', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(56, '提现申请提交通知', 'commission_apply', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(57, '提现申请完成审核通知', 'commission_check', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(58, '佣金打款通知', 'commission_pay', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(59, '分销商等级升级通知', 'commission_upgrade', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(60, '成为股东通知', 'globonus_become', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'globonus', '股东消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(61, '股东等级升级通知', 'globonus_upgrade', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'globonus', '股东消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(62, '分红发放通知', 'globonus_pay', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'globonus', '股东消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(63, '奖励发放通知', 'article', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'article', '文章营销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(64, '成为区域代理通知', 'abonus_become', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'abonus', '区域代理消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(65, '省级代理等级升级通知', 'abonus_upgrade1', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'abonus', '区域代理消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(66, '市级代理等级升级通知', 'abonus_upgrade2', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'abonus', '区域代理消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(67, '区级代理等级升级通知', 'abonus_upgrade3', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'abonus', '区域代理消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(68, '区域代理分红发放通知', 'abonus_pay', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'abonus', '区域代理消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(69, '入驻申请通知', 'merch_apply', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'merch', '商家通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(70, '提现申请提交通知', 'merch_applymoney', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'merch', '商家通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(71, '社区会员评论通知', 'reply', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sns', '人人社区消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(51, '社区会员升级通知', 'sns', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'sns', '人人社区消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(72, '修改地址卖家通知', 'cycelbuy_seller_address', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'cycelbuy', '周期购消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(73, '修改收货时间卖家通知', 'cycelbuy_seller_date', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'cycelbuy', '周期购消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(74, '周期购定时发货通知', 'cycelbuy_timing', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'cycelbuy', '周期购消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(75, '修改收货时间买家通知', 'cycelbuy_buyer_date', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'cycelbuy', '周期购消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(76, '修改地址买家通知', 'cycelbuy_buyer_address', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'cycelbuy', '周期购消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(77, '分销提现申请提醒', 'commission_applymoney', 'OPENTM415477060', NULL, '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'commission', '分销消息通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(80, '成为团长通知', 'dividend_become', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'dividend', '团队分红通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(81, '成为团长通知(卖家)', 'dividend_become_saler', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'dividend', '团队分红通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(82, '团员成为团长通知', 'dividend_downline_become', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'dividend', '团队分红通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(83, '团长提现通知', 'dividend_apply', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'dividend', '团队分红通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(84, '提现审核完成通知', 'dividend_check', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'dividend', '团队分红通知', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(85, '好友瓜分券活动发起通知', 'friendcoupon_launch', 'OPENTM415477060', '', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'friendcoupon', '好友瓜分券', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(86, '好友瓜分券活动完成通知', 'friendcoupon_complete', 'OPENTM415477060', ' ', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'friendcoupon', '好友瓜分券', 0);
INSERT INTO `ims_ewei_shop_member_message_template_type` (`id`, `name`, `typecode`, `templatecode`, `templateid`, `templatename`, `content`, `typegroup`, `groupname`, `showtotaladd`) VALUES(87, '好友瓜分券活动失败通知', 'friendcoupon_failed', 'OPENTM415477060', ' ', '业务处理通知', '{{first.DATA}}业务类型：{{keyword1.DATA}}处理状态：{{keyword2.DATA}}处理内容：{{keyword3.DATA}}{{remark.DATA}}', 'friendcoupon', '好友瓜分券', 0);

SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `ims_ewei_shop_abonus_bill` DROP COLUMN `ceshi`;
ALTER TABLE `ims_ewei_shop_article` DROP INDEX `idx_article_content`;
ALTER TABLE `ims_ewei_shop_article` MODIFY COLUMN `article_keyword2`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `article_keyword`;
ALTER TABLE `ims_ewei_shop_article` MODIFY COLUMN `uniacid`  int(11) NOT NULL DEFAULT 0 AFTER `article_state`;
ALTER TABLE `ims_ewei_shop_article_category` MODIFY COLUMN `displayorder`  int(11) NOT NULL DEFAULT 0 AFTER `category_name`;
ALTER TABLE `ims_ewei_shop_article_category` MODIFY COLUMN `isshow`  tinyint(1) NOT NULL DEFAULT 0 AFTER `displayorder`;
ALTER TABLE `ims_ewei_shop_article_sys` MODIFY COLUMN `article_source`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `article_keyword`;
ALTER TABLE `ims_ewei_shop_bargain_account` ADD PRIMARY KEY (`id`);
ALTER TABLE `ims_ewei_shop_cashier_pay_log` MODIFY COLUMN `payopenid`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `openid`;
ALTER TABLE `ims_ewei_shop_category` MODIFY COLUMN `level`  tinyint(3) NULL DEFAULT NULL AFTER `ishome`;
ALTER TABLE `ims_ewei_shop_commission_apply` MODIFY COLUMN `alipay1`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `bankcard`;
ALTER TABLE `ims_ewei_shop_commission_apply` MODIFY COLUMN `bankname1`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `alipay1`;
ALTER TABLE `ims_ewei_shop_commission_apply` MODIFY COLUMN `bankcard1`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `bankname1`;
ALTER TABLE `ims_ewei_shop_commission_apply` MODIFY COLUMN `repurchase`  decimal(10,2) NULL DEFAULT 0.00 AFTER `bankcard1`;
ALTER TABLE `ims_ewei_shop_commission_level` MODIFY COLUMN `ordermoney`  decimal(10,2) NULL DEFAULT 0.00 AFTER `commission3`;
ALTER TABLE `ims_ewei_shop_commission_level` MODIFY COLUMN `ordercount`  int(11) NULL DEFAULT 0 AFTER `ordermoney`;
ALTER TABLE `ims_ewei_shop_commission_level` MODIFY COLUMN `downcount`  int(11) NULL DEFAULT 0 AFTER `ordercount`;
ALTER TABLE `ims_ewei_shop_commission_level` DROP COLUMN `withdraw`;
ALTER TABLE `ims_ewei_shop_commission_level` DROP COLUMN `repurchase`;
ALTER TABLE `ims_ewei_shop_commission_log` MODIFY COLUMN `type`  tinyint(3) NULL DEFAULT 0 AFTER `commission_pay`;
ALTER TABLE `ims_ewei_shop_coupon` MODIFY COLUMN `pwdkey2`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `pwdkey`;
ALTER TABLE `ims_ewei_shop_creditshop_log` MODIFY COLUMN `transid`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `verifyopenid`;
ALTER TABLE `ims_ewei_shop_creditshop_log` MODIFY COLUMN `dispatchtransid`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `transid`;
ALTER TABLE `ims_ewei_shop_designer` DROP INDEX `idx_keyword`;
ALTER TABLE `ims_ewei_shop_diypage` MODIFY COLUMN `diyadv`  int(11) NOT NULL DEFAULT 0 AFTER `diymenu`;
ALTER TABLE `ims_ewei_shop_exhelper_senduser` MODIFY COLUMN `province`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `isdefault`;
ALTER TABLE `ims_ewei_shop_exhelper_senduser` MODIFY COLUMN `city`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `province`;
ALTER TABLE `ims_ewei_shop_exhelper_senduser` MODIFY COLUMN `area`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `city`;
ALTER TABLE `ims_ewei_shop_exhelper_sys` MODIFY COLUMN `ip_cloud`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `ip`;
ALTER TABLE `ims_ewei_shop_exhelper_sys` MODIFY COLUMN `ebusiness`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `is_cloud`;
ALTER TABLE `ims_ewei_shop_exhelper_sys` MODIFY COLUMN `apikey`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `ebusiness`;
ALTER TABLE `ims_ewei_shop_goods` DROP INDEX `idx_buygroups`;
ALTER TABLE `ims_ewei_shop_goods` DROP INDEX `idx_showgroups`;
ALTER TABLE `ims_ewei_shop_goods` DROP INDEX `idx_buylevels`;
ALTER TABLE `ims_ewei_shop_goods` DROP INDEX `idx_tcate`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `tcate`  int(11) NULL DEFAULT 0 AFTER `ccate`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `credit`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `weight`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `isdiscount_title`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `isdiscount`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `isdiscount_time`  int(11) NULL DEFAULT 0 AFTER `isdiscount_title`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `isdiscount_discounts`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `isdiscount_time`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `commission`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `commission3_pay`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `catch_id`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `score`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `catch_url`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `catch_id`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `catch_source`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `catch_url`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `followurl`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `needfollow`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `shorttitle`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `deduct`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `detail_logo`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `tcates`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `detail_shopname`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `detail_logo`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `detail_totaltitle`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `detail_shopname`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `detail_btntext1`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `detail_totaltitle`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `detail_btnurl1`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `detail_btntext1`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `detail_btntext2`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `detail_btnurl1`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `detail_btnurl2`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `detail_btntext2`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `edareas`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `ednum`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `sharebtn`  tinyint(1) NOT NULL DEFAULT 0 AFTER `subtitle`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `merchid`  int(11) NULL DEFAULT 0 AFTER `sharebtn`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `checked`  tinyint(3) NULL DEFAULT 0 AFTER `merchid`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `thumb_first`  tinyint(3) NULL DEFAULT 0 AFTER `checked`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `merchsale`  tinyint(1) NULL DEFAULT 0 AFTER `thumb_first`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `keywords`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `merchsale`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `labelname`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `keywords`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `autoreceive`  int(11) NULL DEFAULT 0 AFTER `labelname`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `cannotrefund`  tinyint(3) NULL DEFAULT 0 AFTER `autoreceive`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `bargain`  int(11) NULL DEFAULT 0 AFTER `cannotrefund`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `buyagain`  decimal(10,2) NULL DEFAULT 0.00 AFTER `bargain`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `buyagain_islong`  tinyint(1) NULL DEFAULT 0 AFTER `buyagain`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `buyagain_condition`  tinyint(1) NULL DEFAULT 0 AFTER `buyagain_islong`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `buyagain_sale`  tinyint(1) NULL DEFAULT 0 AFTER `buyagain_condition`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `buyagain_commission`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `buyagain_sale`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `buyagain_price`  decimal(10,2) NULL DEFAULT 0.00 AFTER `buyagain_commission`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `diypage`  int(11) NULL DEFAULT NULL AFTER `buyagain_price`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `cashier`  tinyint(1) NULL DEFAULT 0 AFTER `diypage`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `isendtime`  tinyint(3) NOT NULL DEFAULT 0 AFTER `cashier`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `usetime`  int(11) NOT NULL DEFAULT 0 AFTER `isendtime`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `endtime`  int(11) NOT NULL DEFAULT 0 AFTER `usetime`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `merchdisplayorder`  int(11) NOT NULL DEFAULT 0 AFTER `endtime`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `exchange_stock`  int(11) NULL DEFAULT 0 AFTER `merchdisplayorder`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `exchange_postage`  decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `exchange_stock`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `ispresell`  tinyint(3) NOT NULL DEFAULT 0 AFTER `exchange_postage`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `presellprice`  decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `ispresell`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `presellover`  tinyint(3) NOT NULL DEFAULT 0 AFTER `presellprice`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `presellovertime`  int(11) NOT NULL AFTER `presellover`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `presellstart`  tinyint(3) NOT NULL DEFAULT 0 AFTER `presellovertime`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `preselltimestart`  int(11) NOT NULL DEFAULT 0 AFTER `presellstart`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `presellend`  tinyint(3) NOT NULL DEFAULT 0 AFTER `preselltimestart`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `preselltimeend`  int(11) NOT NULL DEFAULT 0 AFTER `presellend`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `presellsendtype`  tinyint(3) NOT NULL DEFAULT 0 AFTER `preselltimeend`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `presellsendstatrttime`  int(11) NOT NULL DEFAULT 0 AFTER `presellsendtype`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `presellsendtime`  int(11) NOT NULL DEFAULT 0 AFTER `presellsendstatrttime`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `edareas_code`  text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `presellsendtime`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `unite_total`  tinyint(3) NOT NULL DEFAULT 0 AFTER `edareas_code`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `threen`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `unite_total`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `intervalfloor`  tinyint(1) NULL DEFAULT 0 AFTER `threen`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `intervalprice`  varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `intervalfloor`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `isfullback`  tinyint(3) NOT NULL DEFAULT 0 AFTER `intervalprice`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `isstatustime`  tinyint(3) NOT NULL DEFAULT 0 AFTER `isfullback`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `statustimestart`  int(10) NOT NULL DEFAULT 0 AFTER `isstatustime`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `statustimeend`  int(10) NOT NULL DEFAULT 0 AFTER `statustimestart`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `nosearch`  tinyint(1) NOT NULL DEFAULT 0 AFTER `statustimeend`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `showsales`  tinyint(3) NOT NULL DEFAULT 1 AFTER `nosearch`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `islive`  int(11) NOT NULL DEFAULT 0 AFTER `showsales`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `liveprice`  decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `islive`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `opencard`  tinyint(1) NULL DEFAULT 0 AFTER `liveprice`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `cardid`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `opencard`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `verifygoodstype`  tinyint(1) NOT NULL DEFAULT 0 AFTER `cardid`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `verifygoodsnum`  int(11) NULL DEFAULT 1 AFTER `verifygoodstype`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `verifygoodsdays`  int(11) NULL DEFAULT 1 AFTER `verifygoodsnum`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `verifygoodslimittype`  tinyint(1) NULL DEFAULT 0 AFTER `verifygoodsdays`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `verifygoodslimitdate`  int(11) NULL DEFAULT 0 AFTER `verifygoodslimittype`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `minliveprice`  decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `verifygoodslimitdate`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `maxliveprice`  decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `minliveprice`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `dowpayment`  decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `maxliveprice`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `tempid`  int(11) NOT NULL DEFAULT 0 AFTER `dowpayment`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `isstoreprice`  tinyint(11) NOT NULL DEFAULT 0 AFTER `tempid`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `beforehours`  int(11) NOT NULL DEFAULT 0 AFTER `isstoreprice`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `officthumb`  varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `video`;
ALTER TABLE `ims_ewei_shop_goods` MODIFY COLUMN `manydeduct2`  tinyint(1) NULL DEFAULT 0 AFTER `isforceverifystore`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `taobaoid`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `taotaoid`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `taobaourl`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `saleupdate42392`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `saleupdate`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `minpriceupdated`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `saleupdate40170`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `saleupdate35843`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `saleupdate33219`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `saleupdate32484`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `saleupdate36586`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `saleupdate53481`;
ALTER TABLE `ims_ewei_shop_goods` DROP COLUMN `saleupdate30424`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `goodssn`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `uniacid`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `productsn`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `goodssn`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `showstock`  tinyint(2) NOT NULL AFTER `category`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `goodsnum`  int(11) NOT NULL DEFAULT 1 AFTER `groupsprice`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `purchaselimit`  int(11) NOT NULL DEFAULT 0 AFTER `goodsnum`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `single`  tinyint(2) NOT NULL DEFAULT 0 AFTER `purchaselimit`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `dispatchtype`  tinyint(2) NOT NULL AFTER `units`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `dispatchid`  int(11) NOT NULL AFTER `dispatchtype`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `isindex`  tinyint(3) NOT NULL DEFAULT 0 AFTER `status`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `followurl`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `followtext`;
ALTER TABLE `ims_ewei_shop_groups_goods` MODIFY COLUMN `thumb_url`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `deduct`;
ALTER TABLE `ims_ewei_shop_groups_goods` DROP COLUMN `ishot`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `credit`  int(11) NULL DEFAULT 0 AFTER `paytime`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `creditmoney`  decimal(11,2) NULL DEFAULT 0.00 AFTER `credit`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `dispatchid`  int(11) NULL DEFAULT NULL AFTER `pay_type`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `addressid`  int(11) NOT NULL DEFAULT 0 AFTER `dispatchid`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `address`  varchar(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `addressid`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `discount`  decimal(10,2) NULL DEFAULT 0.00 AFTER `heads`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `canceltime`  int(11) NOT NULL DEFAULT 0 AFTER `starttime`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `finishtime`  int(11) NOT NULL DEFAULT 0 AFTER `createtime`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `refundid`  int(11) NOT NULL DEFAULT 0 AFTER `finishtime`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `refundstate`  tinyint(2) NOT NULL DEFAULT 0 AFTER `refundid`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `refundtime`  int(11) NOT NULL DEFAULT 0 AFTER `refundstate`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `express`  varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `refundtime`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `expresscom`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `express`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `expresssn`  varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `expresscom`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `sendtime`  int(45) NULL DEFAULT 0 AFTER `expresssn`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `remark`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `sendtime`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `remarkclose`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `remark`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `remarksend`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `remarkclose`;
ALTER TABLE `ims_ewei_shop_groups_order` MODIFY COLUMN `message`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `remarksend`;
ALTER TABLE `ims_ewei_shop_groups_order` DROP COLUMN `delete`;
ALTER TABLE `ims_ewei_shop_groups_order_refund` MODIFY COLUMN `refundtime`  varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `rtype`;
ALTER TABLE `ims_ewei_shop_groups_set` MODIFY COLUMN `followqrcode`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `followurl`;
ALTER TABLE `ims_ewei_shop_groups_set` MODIFY COLUMN `share_url`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `share_desc`;
ALTER TABLE `ims_ewei_shop_live_goods` ROW_FORMAT=Fixed;
ALTER TABLE `ims_ewei_shop_live_goods_option` ROW_FORMAT=Fixed;
ALTER TABLE `ims_ewei_shop_live_status` ROW_FORMAT=Fixed;
ALTER TABLE `ims_ewei_shop_member` DROP INDEX `idx_groupid`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `nickname_wechat`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `nickname`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `diymaxcredit`  tinyint(3) NULL DEFAULT 0 AFTER `credit2`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `maxcredit`  int(11) NULL DEFAULT 0 AFTER `diymaxcredit`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `avatar_wechat`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `avatar`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `agentnotupgrade`  int(11) NULL DEFAULT 0 AFTER `childtime`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `username`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `agentblack`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `diymemberdataid`  int(11) NULL DEFAULT 0 AFTER `diymemberid`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `diymemberdata`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `diymemberdataid`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `diycommissionid`  int(11) NULL DEFAULT 0 AFTER `diymemberdata`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `diycommissiondataid`  int(11) NULL DEFAULT 0 AFTER `diycommissionid`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `diycommissiondata`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `diycommissiondataid`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `isblack`  int(11) NULL DEFAULT 0 AFTER `diycommissiondata`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `diyaagentid`  int(11) NULL DEFAULT 0 AFTER `aagentnotupgrade`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `diyaagentdata`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `diyaagentid`;
ALTER TABLE `ims_ewei_shop_member` MODIFY COLUMN `diyaagentfields`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `diyaagentdata`;
ALTER TABLE `ims_ewei_shop_member` DROP COLUMN `commission`;
ALTER TABLE `ims_ewei_shop_member` DROP COLUMN `commission_pay`;
ALTER TABLE `ims_ewei_shop_member_cart` MODIFY COLUMN `merchid`  int(11) NULL DEFAULT 0 AFTER `selected`;
ALTER TABLE `ims_ewei_shop_member_cart` MODIFY COLUMN `isnewstore`  tinyint(3) NOT NULL DEFAULT 0 AFTER `merchid`;
ALTER TABLE `ims_ewei_shop_member_credit_record` ADD COLUMN `presentcredit`  decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `module`;
ALTER TABLE `ims_ewei_shop_member_level` MODIFY COLUMN `buygoods`  tinyint(1) NOT NULL DEFAULT 0 AFTER `enabled`;
ALTER TABLE `ims_ewei_shop_member_level` MODIFY COLUMN `goodsids`  text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `buygoods`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `transid`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `rechargetype`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `isborrow`  tinyint(3) NULL DEFAULT 0 AFTER `couponid`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `borrowopenid`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `isborrow`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `apppay`  tinyint(3) NOT NULL DEFAULT 0 AFTER `borrowopenid`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `alipay`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `apppay`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `bankname`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `alipay`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `bankcard`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `bankname`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `realname`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `bankcard`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `applytype`  tinyint(3) NOT NULL DEFAULT 0 AFTER `realname`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `sendmoney`  decimal(10,2) NULL DEFAULT 0.00 AFTER `applytype`;
ALTER TABLE `ims_ewei_shop_member_log` MODIFY COLUMN `senddata`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `sendmoney`;
ALTER TABLE `ims_ewei_shop_member_message_template_type` MODIFY COLUMN `typegroup`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `content`;
ALTER TABLE `ims_ewei_shop_member_message_template_type` MODIFY COLUMN `groupname`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `typegroup`;
ALTER TABLE `ims_ewei_shop_member_message_template_type` DROP PRIMARY KEY;
ALTER TABLE `ims_ewei_shop_member_printer` MODIFY COLUMN `merchid`  int(11) NULL DEFAULT 0 AFTER `uniacid`;
ALTER TABLE `ims_ewei_shop_member_printer_template` MODIFY COLUMN `merchid`  int(11) NULL DEFAULT 0 AFTER `uniacid`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `verifytime`  int(11) NULL DEFAULT 0 AFTER `verifyopenid`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `closereason`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `storeid`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `remarksaler`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `closereason`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `merchid`  int(11) NULL DEFAULT 0 AFTER `verifycodes`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `apppay`  tinyint(3) NOT NULL DEFAULT 0 AFTER `borrowopenid`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `coupongoodprice`  decimal(10,2) NULL DEFAULT 1.00 AFTER `apppay`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `buyagainprice`  decimal(10,2) NULL DEFAULT 0.00 AFTER `coupongoodprice`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `ispackage`  tinyint(3) NULL DEFAULT 0 AFTER `buyagainprice`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `packageid`  int(11) NULL DEFAULT 0 AFTER `ispackage`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `taskdiscountprice`  decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `packageid`;
ALTER TABLE `ims_ewei_shop_order` MODIFY COLUMN `iswxappcreate`  tinyint(1) NULL DEFAULT 0 AFTER `wxapp_prepay_id`;
ALTER TABLE `ims_ewei_shop_order` DROP COLUMN `authorid`;
ALTER TABLE `ims_ewei_shop_order` DROP COLUMN `isauthor`;
ALTER TABLE `ims_ewei_shop_order` DROP COLUMN `ces`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `diyformdata`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `commissions`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `diyformfields`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `diyformdata`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `diyformdataid`  int(11) NULL DEFAULT 0 AFTER `diyformfields`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `openid`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `diyformdataid`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `rstate`  tinyint(3) NULL DEFAULT 0 AFTER `diyformid`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `refundtime`  int(11) NULL DEFAULT 0 AFTER `rstate`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `canbuyagain`  tinyint(1) NULL DEFAULT 0 AFTER `parentorderid`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `seckill`  tinyint(3) NULL DEFAULT 0 AFTER `canbuyagain`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `seckill_taskid`  int(11) NULL DEFAULT 0 AFTER `seckill`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `seckill_roomid`  int(11) NULL DEFAULT 0 AFTER `seckill_taskid`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `seckill_timeid`  int(11) NULL DEFAULT 0 AFTER `seckill_roomid`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `sendtype`  tinyint(3) NOT NULL DEFAULT 0 AFTER `seckill_timeid`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `expresscom`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `sendtype`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `expresssn`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `expresscom`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `express`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `expresssn`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `sendtime`  int(11) NOT NULL AFTER `express`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `finishtime`  int(11) NOT NULL AFTER `sendtime`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `remarksend`  text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `finishtime`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `prohibitrefund`  tinyint(3) NOT NULL DEFAULT 0 AFTER `remarksend`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `storeid`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `prohibitrefund`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `trade_time`  int(11) NOT NULL DEFAULT 0 AFTER `storeid`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `optime`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `trade_time`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `tdate_time`  int(11) NOT NULL DEFAULT 0 AFTER `optime`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `dowpayment`  decimal(10,2) NOT NULL DEFAULT 0.00 AFTER `tdate_time`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `peopleid`  int(11) NOT NULL DEFAULT 0 AFTER `dowpayment`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `esheetprintnum`  int(11) NOT NULL DEFAULT 0 AFTER `peopleid`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `ordercode`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' AFTER `esheetprintnum`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `title`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `ordercode`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `consume`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `title`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `single_refundid`  int(11) NOT NULL DEFAULT 0 AFTER `consume`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `single_refundstate`  tinyint(3) NOT NULL DEFAULT 0 AFTER `single_refundid`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `single_refundtime`  int(11) NOT NULL DEFAULT 0 AFTER `single_refundstate`;
ALTER TABLE `ims_ewei_shop_order_goods` MODIFY COLUMN `fullbackid`  int(11) NOT NULL DEFAULT 0 AFTER `single_refundtime`;
ALTER TABLE `ims_ewei_shop_order_goods` DROP COLUMN `is_make`;
ALTER TABLE `ims_ewei_shop_order_refund` MODIFY COLUMN `realprice`  decimal(10,2) NULL DEFAULT 0.00 AFTER `refundtype`;
ALTER TABLE `ims_ewei_shop_order_refund` MODIFY COLUMN `refundtime`  int(11) NULL DEFAULT 0 AFTER `realprice`;
ALTER TABLE `ims_ewei_shop_perm_log` DROP INDEX `idx_op`;
ALTER TABLE `ims_ewei_shop_perm_log` DROP INDEX `idx_type`;
ALTER TABLE `ims_ewei_shop_perm_log` MODIFY COLUMN `ip`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `op`;
ALTER TABLE `ims_ewei_shop_perm_plugin` DROP INDEX `idx_acid`;
ALTER TABLE `ims_ewei_shop_perm_role` MODIFY COLUMN `perms2`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `perms`;
ALTER TABLE `ims_ewei_shop_perm_user` MODIFY COLUMN `perms2`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `perms`;
ALTER TABLE `ims_ewei_shop_plugin` DROP INDEX `idx_identity`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `keyword2`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `keyword`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `resptype`  tinyint(3) NULL DEFAULT 0 AFTER `isdefault`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `resptext`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `resptype`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `scantext`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `recmoney`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `subtext`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `scantext`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `beagent`  tinyint(3) NULL DEFAULT 0 AFTER `subtext`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `bedown`  tinyint(3) NULL DEFAULT 0 AFTER `beagent`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `isopen`  tinyint(3) NULL DEFAULT 0 AFTER `bedown`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `opentext`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `isopen`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `openurl`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `opentext`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `subpaycontent`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `paytype`;
ALTER TABLE `ims_ewei_shop_poster` MODIFY COLUMN `recpaycontent`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `subpaycontent`;
ALTER TABLE `ims_ewei_shop_postera` MODIFY COLUMN `keyword2`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '' AFTER `keyword`;
ALTER TABLE `ims_ewei_shop_postera` MODIFY COLUMN `resptype`  tinyint(3) NULL DEFAULT 0 AFTER `isdefault`;
ALTER TABLE `ims_ewei_shop_postera` MODIFY COLUMN `resptext`  text CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `resptype`;
ALTER TABLE `ims_ewei_shop_postera_log` DROP INDEX `idx_from_openid`;
ALTER TABLE `ims_ewei_shop_poster_log` DROP INDEX `idx_from_openid`;
ALTER TABLE `ims_ewei_shop_poster_qr` DROP INDEX `idx_openid`;
ALTER TABLE `ims_ewei_shop_poster_qr` MODIFY COLUMN `posterid`  int(11) NULL DEFAULT 0 AFTER `qrimg`;
ALTER TABLE `ims_ewei_shop_poster_scan` DROP INDEX `idx_openid`;
CREATE TABLE `ims_ewei_shop_queue` (
`id`  int(11) NOT NULL AUTO_INCREMENT ,
`channel`  varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL ,
`job`  blob NOT NULL ,
`pushed_at`  int(11) NOT NULL ,
`ttr`  int(11) NOT NULL ,
`delay`  int(11) NOT NULL DEFAULT 0 ,
`priority`  int(11) UNSIGNED NOT NULL DEFAULT 1024 ,
`reserved_at`  int(11) NULL DEFAULT NULL ,
`attempt`  int(11) NULL DEFAULT NULL ,
`done_at`  int(11) NULL DEFAULT NULL ,
PRIMARY KEY (`id`),
INDEX `channel` (`channel`(250)) USING BTREE ,
INDEX `reserved_at` (`reserved_at`) USING BTREE ,
INDEX `priority` (`priority`) USING BTREE 
)
ENGINE=MyISAM
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
CHECKSUM=0
ROW_FORMAT=Dynamic
DELAY_KEY_WRITE=0
;
ALTER TABLE `ims_ewei_shop_quick` MODIFY COLUMN `merchid`  int(11) NOT NULL DEFAULT 0 AFTER `uniacid`;
ALTER TABLE `ims_ewei_shop_quick` MODIFY COLUMN `type`  tinyint(3) NULL DEFAULT 0 AFTER `enter_icon`;
ALTER TABLE `ims_ewei_shop_refund_address` MODIFY COLUMN `openid`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '0' AFTER `uniacid`;
ALTER TABLE `ims_ewei_shop_sms_set` MODIFY COLUMN `aliyun`  tinyint(3) NOT NULL DEFAULT 0 AFTER `dayu_secret`;
ALTER TABLE `ims_ewei_shop_sms_set` MODIFY COLUMN `aliyun_appcode`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL AFTER `aliyun`;
ALTER TABLE `ims_ewei_shop_store` MODIFY COLUMN `type`  tinyint(1) NULL DEFAULT 0 AFTER `status`;
ALTER TABLE `ims_ewei_shop_sysset` MODIFY COLUMN `sec`  longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `plugins`;
ALTER TABLE `ims_ewei_shop_system_setting` MODIFY COLUMN `contact`  longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `casebanner`;
ALTER TABLE `ims_ewei_shop_upwxapp_log` MODIFY COLUMN `is_goods`  tinyint(1) NULL DEFAULT 0 AFTER `type`;
ALTER TABLE `ims_ewei_shop_wxapp_bind` ROW_FORMAT=Fixed;
SET FOREIGN_KEY_CHECKS=1;
");